from . import workorder
from . import sale
from . import vehicle
from . import res_partner
from . import account_invoice
from . import hr_employee
from . import product_template
from . import res_company
from . import sale_excel