{
    'name': 'tickets_management',
    'version': '1.0.0',
    'category': 'ticketing module',
    'sequence': -100,
    'author': 'Devendra Stha',
    'summary': 'Generating tickets for support',
    'description': """
        This module provides support for clients to solve their problems.
    """,
    'depends': ['hr', 'mail','contacts'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/data_view.xml',
        'views/view_ticket_management.xml',
        'views/configuration_view.xml',
        'views/reporting_view.xml',
        'views/dashboard_view.xml',
        'views/closed_view.xml',
        'views/myticket_view.xml',
        'views/mail_templete_data.xml',
        'views/team_view.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
