{
    'name': "CRMIC CHALLAN",
    'version': 'GAP-1.0.1',
    'summary': 'Kalashsoap ',
     'description': "Kalahsoap",
    'sequence' : "1",
    'author': "Sudarshan Shrestha",
    'company': 'CRMIC',
    'category': 'Extra Tools',
    'data': [
        # 'security/security.xml',
        'security/ir.model.access.csv',
        # 'views/stock_view.xml',
        'views/manufacturing_view.xml',
        'views/purchase_view.xml',
        'reports/challan_report.xml',
        'reports/challan_template.xml',
    ],
    'depends': ['base', 'mail', 'stock', 'purchase', 'mrp'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}